# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Openshift Route plugin CI
on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "*"

jobs:
  unit-tests:
    name: Unit tests running
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: './go.mod'

      - name: Checkout code
        uses: actions/checkout@v3.1.0

      - name: Unit tests running
        run: |
          make test

  linting:
    name: Go code lint and gosec
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: './go.mod'

      - name: Checkout code
        uses: actions/checkout@v3.1.0

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          args: --verbose --timeout 6m

      - name: Run gosec
        run: |
          make gosec

  build:
    name: Build creation
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: './go.mod'

      - name: Checkout code
        uses: actions/checkout@v3.1.0

      - name: Build creation
        run: |
          make build
